name: Test

on:
  # Triggers the workflow on push or pull request events.
  push:
    # This should disable running the workflow on tags, according to the
    # on.<push|pull_request>.<branches|tags> GitHub Actions docs.
    branches:
      - "*"
  pull_request:
    types: [opened, reopened, synchronize]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs.
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ruby-head]
    name: Test (ruby=${{ matrix.ruby }})
    steps:
      - name: Set Up Actions
        uses: actions/checkout@v3
      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
           ruby-version: ${{ matrix.ruby }}
           bundler-cache: true
      - name: Test
        run: bundle exec rake test
